[build]
builder = "nixpacks"

[deploy]
# Run database migrations before starting the app
startCommand = "startCommand = "npx prisma db push --accept-data-loss && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[healthcheck]
# Check if the app is responding
httpPath = "/api/health"
timeout = 30
interval = 60

