import { Metadata } from 'next';
import { Card, CardContent } from '@/components/ui/card';
import { AlertTriangle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Disclaimer | Robot Recruit AI',
  description: 'Important disclaimers about AI-generated content and service limitations',
};

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="mb-8 flex items-center gap-4">
        <div className="p-3 bg-yellow-500/20 rounded-lg">
          <AlertTriangle className="w-8 h-8 text-yellow-400" />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-white font-orbitron">Disclaimer</h1>
          <p className="text-gray-400">Last Updated: 25 January 2025</p>
        </div>
      </div>

      <Card className="bg-gray-900/50 border-gray-800">
        <CardContent className="prose prose-invert max-w-none p-8 space-y-6">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Important Notice</h2>
            <p className="text-gray-300">
              This disclaimer governs your use of RobotRecruit.AI (the "Service"), operated by AI Works UK, registered in England and Wales. By accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.
            </p>
          </section>

          <section className="bg-red-900/20 border-2 border-red-600/50 rounded-lg p-6">
            <h2 className="text-2xl font-bold text-red-300 mb-4">⚠️ Critical AI Content Disclaimer</h2>
            <p className="text-gray-200 font-semibold mb-4">
              ALL CONTENT GENERATED BY AI BOTS IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY AND COMES WITH SIGNIFICANT LIMITATIONS
            </p>
            
            <h3 className="text-xl font-semibold text-yellow-400 mb-3">1. No Guarantee of Accuracy</h3>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li><strong>AI-Generated Content May Be Incorrect:</strong> Artificial intelligence models can and do produce inaccurate, incomplete, outdated, or misleading information</li>
              <li><strong>"Hallucinations":</strong> AI may confidently generate plausible-sounding but completely false information</li>
              <li><strong>No Verification:</strong> AI responses are not fact-checked, verified, or reviewed by human experts before being presented to you</li>
              <li><strong>Outdated Information:</strong> AI training data has knowledge cutoff dates and may not reflect current events, laws, or best practices</li>
              <li><strong>Bias and Errors:</strong> AI models may reflect biases, errors, or gaps present in their training data</li>
            </ul>

            <h3 className="text-xl font-semibold text-yellow-400 mb-3 mt-6">2. Not Professional Advice</h3>
            <p className="text-gray-300 mb-3">
              <strong>AI-generated content does NOT constitute professional advice of any kind, including but not limited to:</strong>
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li><strong>Medical Advice:</strong> Do not use AI for diagnosis, treatment, or medical decisions. Always consult qualified healthcare professionals</li>
              <li><strong>Legal Advice:</strong> Do not rely on AI for legal matters. Always consult licensed solicitors or barristers</li>
              <li><strong>Financial Advice:</strong> Do not use AI for investment, tax, or financial planning decisions. Consult certified financial advisors</li>
              <li><strong>Mental Health Support:</strong> AI is not a substitute for therapy, counseling, or crisis intervention services</li>
              <li><strong>Safety-Critical Decisions:</strong> Do not rely on AI for decisions that could impact health, safety, or welfare</li>
            </ul>

            <h3 className="text-xl font-semibold text-yellow-400 mb-3 mt-6">3. Emergency Situations</h3>
            <div className="bg-red-800/30 border border-red-500/50 rounded p-4 mb-4">
              <p className="text-red-200 font-bold mb-2">⚠️ IF YOU ARE EXPERIENCING A MEDICAL OR MENTAL HEALTH EMERGENCY:</p>
              <ul className="list-disc pl-6 text-gray-200 space-y-1">
                <li><strong>UK:</strong> Call 999 for emergencies or 111 for urgent medical advice</li>
                <li><strong>Mental Health Crisis:</strong> Call Samaritans 116 123 (free, 24/7)</li>
                <li><strong>Suicide Prevention:</strong> Call 0800 689 5652 or text "SHOUT" to 85258</li>
              </ul>
              <p className="text-red-200 mt-3">DO NOT use AI chatbots in place of emergency services or crisis intervention.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Your Responsibilities</h2>
            
            <h3 className="text-xl font-semibold text-cyan-400 mb-3">You Must:</h3>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li><strong>Verify All Information:</strong> Independently verify any AI-generated information before relying on it</li>
              <li><strong>Use Critical Thinking:</strong> Evaluate AI responses with skepticism and common sense</li>
              <li><strong>Consult Professionals:</strong> Seek qualified professional advice for important decisions</li>
              <li><strong>Accept Full Responsibility:</strong> You are solely responsible for any decisions or actions based on AI-generated content</li>
              <li><strong>Understand Limitations:</strong> Recognize that AI is a tool with significant limitations, not an infallible expert</li>
            </ul>

            <h3 className="text-xl font-semibold text-cyan-400 mb-3 mt-6">You Must Not:</h3>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              <li>Rely solely on AI for medical, legal, financial, or safety-critical decisions</li>
              <li>Share highly sensitive or confidential information with AI bots</li>
              <li>Use AI-generated content to harm yourself or others</li>
              <li>Assume AI responses are accurate, complete, or current</li>
              <li>Use the Service for unauthorized professional advice or services</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Limitation of Liability</h2>
            <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
              <p className="text-gray-300 mb-4">
                <strong>TO THE MAXIMUM EXTENT PERMITTED BY UK LAW:</strong>
              </p>
              <ul className="list-disc pl-6 text-gray-300 space-y-2">
                <li>AI Works UK and RobotRecruit.AI are NOT LIABLE for any losses, damages, injuries, or consequences arising from:
                  <ul className="list-circle pl-6 mt-2 space-y-1">
                    <li>Inaccurate, incomplete, or misleading AI-generated content</li>
                    <li>Decisions made based on AI recommendations or information</li>
                    <li>Failure to seek professional advice when appropriate</li>
                    <li>Reliance on AI-generated content for critical decisions</li>
                    <li>Any harm resulting from use of the Service</li>
                  </ul>
                </li>
                <li>The Service is provided "AS IS" without warranties of accuracy, reliability, or fitness for purpose</li>
                <li>We do not guarantee that AI responses will be correct, helpful, or appropriate for your situation</li>
                <li>You use the Service entirely at your own risk</li>
              </ul>
              <p className="text-gray-300 mt-4">
                <em>Nothing in this disclaimer excludes liability for death or personal injury caused by negligence, fraud, or other liability that cannot be excluded under UK law.</em>
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Third-Party AI Services</h2>
            <p className="text-gray-300">
              Our Service uses third-party artificial intelligence services (primarily OpenAI) to generate responses. These third-party services:
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2 mt-4">
              <li>Have their own terms of service and limitations</li>
              <li>May have different data handling practices</li>
              <li>Are not under our direct control</li>
              <li>May experience outages, errors, or changes in functionality</li>
            </ul>
            <p className="text-gray-300 mt-4">
              We are not responsible for the performance, accuracy, or availability of third-party AI services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Service Availability</h2>
            <p className="text-gray-300">
              We do not guarantee that the Service will be:
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2 mt-4">
              <li>Available at all times without interruption</li>
              <li>Free from errors, bugs, or technical issues</li>
              <li>Secure from unauthorized access or cyber threats</li>
              <li>Compatible with all devices or browsers</li>
              <li>Suitable for your specific needs or purposes</li>
            </ul>
            <p className="text-gray-300 mt-4">
              We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Intellectual Property</h2>
            <p className="text-gray-300">
              AI-generated content may not be unique to you. Similar or identical content may be generated for other users. We make no warranties regarding:
            </p>
            <ul className="list-disc pl-6 text-gray-300 space-y-2 mt-4">
              <li>Originality of AI-generated content</li>
              <li>Intellectual property rights in AI-generated content</li>
              <li>Whether AI-generated content infringes third-party rights</li>
              <li>Fitness of AI-generated content for commercial use</li>
            </ul>
            <p className="text-gray-300 mt-4">
              You are responsible for ensuring that any use of AI-generated content complies with applicable laws and does not infringe third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Changes to This Disclaimer</h2>
            <p className="text-gray-300">
              We may update this disclaimer at any time. Changes will be effective upon posting with an updated "Last Updated" date. Your continued use of the Service after changes constitutes acceptance of the updated disclaimer.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Contact Information</h2>
            <div className="bg-gray-800/50 p-6 rounded-lg mt-4">
              <p className="text-gray-300"><strong>Company:</strong> AI Works UK</p>
              <p className="text-gray-300 mt-2"><strong>Trading As:</strong> RobotRecruit.AI</p>
              <p className="text-gray-300 mt-2"><strong>Address:</strong> Coach House, Ways Green, Cheshire, CW7 4AN</p>
              <p className="text-gray-300 mt-2"><strong>Email:</strong> <a href="mailto:service@robotrecruit.ai" className="text-cyan-400 hover:underline">service@robotrecruit.ai</a></p>
            </div>
          </section>

          <section className="bg-yellow-900/20 border border-yellow-500/30 rounded-lg p-6 mt-8">
            <h3 className="text-xl font-semibold text-yellow-400 mb-3">Final Reminder</h3>
            <p className="text-gray-300">
              By using RobotRecruit.AI, you acknowledge that AI-generated content is not a substitute for professional advice, may contain errors, and should be used with caution. You accept full responsibility for verifying information and making informed decisions.
            </p>
            <p className="text-gray-300 mt-4">
              <strong>When in doubt, always consult qualified professionals.</strong>
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}

